#pragma once
#define FC_TARGET_MCU AT32F435G
#define BOARD_NAME LIONBEE_V1
#define MANUFACTURER_ID NBD
#define USBD_PRODUCT_STRING "AT32F435 LionBee V1"

#define USE_LED_STRIP
#define USE_LED_STRIP_STATUS_MODE
#define LED_STRIP_PIN PB1
#define LED0_PIN PB8
#define USE_BEEPER
#define USE_VCP
#define USE_UART5
#define UART5_RX_PIN PB5
#define UART5_TX_PIN PB6
#define USE_I2C
#define USE_I2C_DEVICE_2
#define I2C2_SCL_PIN PB10
#define I2C2_SDA_PIN PB11
#define USE_GPS
#define USE_GPS_NMEA
#define USE_GPS_UBLOX
#define USE_GPS_RESCUE
#define USE_SPI
#define USE_SPI_DMA_ENABLE_LATE
#define USE_SPI_DEVICE_1
#define SPI1_SCK_PIN PA5
#define SPI1_SDI_PIN PA6
#define SPI1_SDO_PIN PA7
#define SPI1_NSS_PIN PA4
#define USE_SPI_DEVICE_2
#define SPI2_SCK_PIN PB13
#define SPI2_SDI_PIN PB14
#define SPI2_SDO_PIN PB15
#define USE_SPI_DEVICE_3
#define SPI3_SCK_PIN PB12
#define SPI3_SDI_PIN PB4
#define SPI3_SDO_PIN PB0
#define USE_ACC
#define USE_GYRO
#define USE_GYRO_EXTI
#define USE_ACCGYRO_BMI270
#define GYRO_1_EXTI_PIN PC13
#define GYRO_1_CS_PIN SPI1_NSS_PIN
#define GYRO_1_SPI_INSTANCE SPI1
#define GYRO_1_ALIGN CW270_DEG
#define DEFAULT_ALIGN_BOARD_PITCH 180
#define DEFAULT_ALIGN_BOARD_YAW 90

// LionBee V1 factory defaults are applied only by PG reset functions.
// Do NOT use USE_TARGET_CONFIG here: it runs targetConfiguration() during
// early boot before the stored config is loaded and changed DShot startup
// behaviour on this board.
#define LIONBEE_V1_FACTORY_PID_DEFAULTS
#define LIONBEE_V1_FACTORY_VTX_DEFAULTS
#define LIONBEE_NBD_RTC6705_COMPAT
#define LIONBEE_V1_FACTORY_IDENTITY_DEFAULTS
#define LIONBEE_V1_FACTORY_ARMING_DEFAULTS
#define LIONBEE_NBD_DSHOT_TIMING_COMPAT
#define LIONBEE_V1_FACTORY_DSHOT_BIDIR
#define LIONBEE_V1_FACTORY_OSD_DEFAULTS
#define LIONBEE_V1_FACTORY_MODE_DEFAULTS
#define LIONBEE_V1_FACTORY_LED_DEFAULTS
#define LIONBEE_V1_FACTORY_VTX_TABLE_DEFAULTS
#define LIONBEE_V1_FACTORY_FULL_RESET_DEFAULTS
#define LIONBEE_AT32_ELRS_TIMER_COMPAT
#define LIONBEE_AT32_RX_SPI_COMPAT

#define USE_OSD
#define USE_OSD_SD
#define USE_MAX7456
#define MAX7456_SPI_CS_PIN PC14
#define MAX7456_SPI_INSTANCE SPI3

#define USE_VTX_RTC6705
#define SPI_SHARED_MAX7456_AND_RTC6705
#define RTC6705_CS_PIN PB2
#define RTC6705_SPI_INSTANCE SPI3
#define RTC6705_EX_POWER_1_PIN PA14
#define RTC6705_EX_POWER_2_PIN PB7
#define RTC6705_DYNAMIC_POWER_CTRL
#define CMS_SKIP_EMPTY_VTX_TABLE_ENTRIES

#define USE_FLASH
#define USE_FLASH_SPI
#define USE_FLASH_M25P16
#define DEFAULT_BLACKBOX_DEVICE BLACKBOX_DEVICE_FLASH
#define FLASH_CS_PIN PC15
#define FLASH_SPI_INSTANCE SPI3

#define USE_RX_SPI
#define USE_RX_EXPRESSLRS
#define USE_ELRSV4
#define USE_RX_SX1280
#undef USE_RX_SX127X
#define RX_SPI_CS_PIN PA8
#define RX_SPI_LED_PIN PB9
#define RX_SPI_EXTI_PIN PB3
#define RX_SPI_BIND_PIN PH2
#define RX_EXPRESSLRS_SPI_RESET_PIN PH3
#define RX_EXPRESSLRS_SPI_BUSY_PIN PA15
#define RX_SPI_INSTANCE SPI2
#define RX_EXPRESSLRS_TIMER_INSTANCE TMR2
#define RX_SPI_LED_INVERTED
#define RX_SPI_PROTOCOL EXPRESSLRS
#define DEFAULT_RX_FEATURE FEATURE_RX_SPI
#define DEFAULT_FEATURES (FEATURE_GPS | FEATURE_TELEMETRY | FEATURE_LED_STRIP | FEATURE_OSD)
#define RX_SPI_DEFAULT_PROTOCOL RX_SPI_EXPRESSLRS

#define USE_BARO
#define USE_BARO_DPS310
#define BARO_I2C_INSTANCE (I2CDEV_2)
#define BARO_BUSTYPE BUS_TYPE_I2C
#define USE_MAG
#define USE_MAG_QMC5883
#define MAG_I2C_INSTANCE (I2CDEV_2)
#define MAG_BUSTYPE BUS_TYPE_I2C
#define GPS_UART SERIAL_PORT_UART5
#define USE_ADC
#define ADC_INSTANCE ADC1
#define ADC1_DMA_OPT 12
#define ADC_VBAT_PIN PA2
#define ADC_CURR_PIN PA3
#define DEFAULT_CURRENT_METER_SCALE 447
#define DEFAULT_VOLTAGE_METER_SCALE 110
#define DEFAULT_CURRENT_METER_SOURCE CURRENT_METER_ADC
#define DEFAULT_VOLTAGE_METER_SOURCE VOLTAGE_METER_ADC
#define MOTOR1_PIN PA1
#define MOTOR2_PIN PA0
#define MOTOR3_PIN PA9
#define MOTOR4_PIN PA10
#define USE_DSHOT_BITBANG
#define USE_DSHOT_TELEMETRY
#define TIMER_PIN_MAPPING \
 TIMER_PIN_MAP(0, PB1, 2, 0) \
 TIMER_PIN_MAP(1, PA1, 1, 0) \
 TIMER_PIN_MAP(2, PA0, 1, 0) \
 TIMER_PIN_MAP(3, PA9, 1, 0) \
 TIMER_PIN_MAP(4, PA10, 1, 0)
#define SYSTEM_HSE_MHZ 8
#define USE_EXTI
#undef USE_TRANSPONDER
#undef USE_RX_PPM
#undef USE_RX_PWM
#undef USE_RX_CC2500
#define TARGET_IO_PORTA 0xffff
#define TARGET_IO_PORTB 0xffff
#define TARGET_IO_PORTC 0xffff
#define TARGET_IO_PORTD 0xffff
#define TARGET_IO_PORTH 0xffff
#define FLASH_PAGE_SIZE ((uint32_t)0x0800)

// LionBee V1 requires the analog MAX7456 display port as its persisted default.
#define LIONBEE_FORCE_MAX7456_DEFAULT
